// Task status enumeration
export type TaskStatus =
  | 'pending'    // Waiting for dependencies
  | 'ready'      // Dependencies satisfied, can be executed
  | 'running'    // Currently executing
  | 'success'    // Completed successfully
  | 'failed'     // Failed
  | 'canceled';  // Canceled by user

// Task kind derived from TaskId prefix (Phase 2)
export type TaskKind =
  | 'prototype'   // PROTO-* tasks (model-generated prototypes)
  | 'audit'       // AUDIT-* tasks (code review/audit)
  | 'frontend'    // FE-* tasks (frontend development)
  | 'backend'     // BE-* tasks (backend development)
  | 'integration' // INT-* tasks (integration/coordination)
  | 'review'      // REVIEW-* tasks (review & sync)
  | 'general';    // Default for unmatched prefixes

// Task scope for domain routing (Phase 2)
export type TaskScope = 'FE' | 'BE' | 'FULL';

// Task definition
export interface Task {
  id: string;
  title: string;
  status: TaskStatus;
  wave: number;
  dependencies: string[];
  estimatedTokens?: number;
  duration?: number;       // Execution time in seconds
  startTime?: string;      // ISO timestamp
  endTime?: string;        // ISO timestamp
  workerId?: number;       // Assigned worker ID
  retryCount?: number;     // Auto-retry count for non-API failures (0 = never retried)
  nextRetryAt?: number;    // Next retry time (epoch ms)
  // API error recovery fields
  hasModifiedCode?: boolean;      // True if the task has used Edit/Write tools
  apiErrorRetryCount?: number;    // API error retry count (separate from retryCount)
  isApiErrorRecovery?: boolean;   // True if this run is recovering from API error
  // Phase 2: Multi-model collaboration fields
  persona?: string;               // e.g., "gemini/cocos-game-expert" - explicit routing
  scope?: TaskScope;              // FE | BE | FULL - domain scope for routing
  taskKind?: TaskKind;            // Derived from TaskId prefix (PROTO/AUDIT/FE/BE/INT)
  metadata?: Record<string, string>;  // Generic key-value for extensible fields
}

// Auto-retry configuration
export interface AutoRetryConfig {
  enabled: boolean;        // Enable auto-retry
  maxRetries: number;      // Max retries after initial run
  baseDelayMs: number;     // Base delay for exponential backoff
}

// Log entry type enumeration
export type LogEntryType =
  | 'start'      // Process start
  | 'tool'       // Tool invocation
  | 'result'     // Tool result
  | 'output'     // Text output
  | 'error'      // Error message
  | 'system';    // System message

// Log entry
export interface LogEntry {
  ts: string;              // Timestamp (HH:mm:ss format)
  type: LogEntryType;
  content: string;
}

// Worker state
export interface WorkerState {
  id: number;
  active: boolean;
  taskId?: string;
  tokenUsage?: string;     // e.g., "10.2k/180k"
  currentTool?: string;    // Currently executing tool
  logs: LogEntry[];
  workerKind?: 'claude' | 'codex' | 'gemini';  // Phase 3: Worker type for UI display
}

// Progress info
export interface Progress {
  completed: number;
  total: number;
}

// Issue severity levels
export type IssueSeverity = 'warning' | 'error' | 'blocker';

// Issue status
export type IssueStatus = 'open' | 'fixed' | 'ignored';

// Issue reported by workers
export interface Issue {
  id: string;                 // Generated by scheduler (hash-based)
  createdAt: string;          // ISO timestamp
  reporterTaskId: string;     // Task that reported this issue
  reporterWorkerId: number;   // Worker that reported this issue
  ownerTaskId?: string;       // Task that should fix this (if known)
  severity: IssueSeverity;
  title: string;
  details?: string;
  files: string[];
  signature?: string;         // For deduplication
  status: IssueStatus;
  occurrences: number;        // How many times this issue was reported
}

// Pause reason for UI display
export type SchedulerPauseReason = 'user' | 'blocker' | 'apiError';

// ============================================================
// Artifact Types (Phase 3: Multi-Model Collaboration)
// ============================================================

export type ArtifactKind = 'diff' | 'files' | 'spec' | 'report' | 'log';

export interface ArtifactRef {
  id: string;
  runId: string;
  taskId: string;
  name: string;
  kind: ArtifactKind;
  mediaType: string;
  sha256: string;
  sizeBytes: number;
  uri: string;
  createdAt: string;
  meta?: Record<string, unknown>;
}

export interface ArtifactDraft {
  name: string;
  kind: ArtifactKind;
  content: Uint8Array | string;
  mediaType?: string;
  meta?: Record<string, unknown>;
}

export interface ArtifactRequirement {
  fromTaskId: string;
  name?: string;
  kind?: ArtifactKind;
  required?: boolean;
  maxBytes?: number;
}

// ============================================================
// Worker Types (Phase 3: Multi-Model Collaboration)
// ============================================================

export type WorkerType = 'claude-cli' | 'codex-cli' | 'gemini-cli';

export interface WorkerCapabilities {
  type: WorkerType;
  model?: string;
  maxConcurrentRuns: number;
  supportsStreaming: boolean;
  supportsArtifacts: boolean;
}

export type WorkerRunPhase = 'starting' | 'running' | 'finishing';

export interface WorkerRunRequest {
  runId: string;
  taskId: string;
  prompt: string;
  projectRoot: string;
  artifactRequirements?: ArtifactRequirement[];
  timeout?: number;
  personaPrompt?: string;  // Persona context to prepend to prompt
}

export interface WorkerRunResult {
  success: boolean;
  durationMs: number;
  artifacts?: ArtifactRef[];
  error?: string;
}

// Scheduler full state (for hydration)
export interface SchedulerFullState {
  running: boolean;
  paused: boolean;
  pausedReason?: SchedulerPauseReason | null;
  filePath: string;
  projectRoot: string;
  tasks: Task[];
  workers: WorkerState[];
  progress: Progress;
  issues: Issue[];
}

// ============================================================
// Server → Client Messages
// ============================================================

export interface TaskUpdateMessage {
  type: 'taskUpdate';
  payload: {
    taskId: string;
    status: TaskStatus;
    duration?: number;
    startTime?: string;
    endTime?: string;
    workerId?: number;
    retryCount?: number;
    nextRetryAt?: number | null;
  };
}

export interface WorkerLogMessage {
  type: 'workerLog';
  payload: {
    workerId: number;
    taskId?: string;
    entry: LogEntry;
  };
}

export interface ProgressMessage {
  type: 'progress';
  payload: Progress;
}

export interface SchedulerStateMessage {
  type: 'schedulerState';
  payload: {
    running: boolean;
    paused: boolean;
    pausedReason?: SchedulerPauseReason | null;
  };
}

export interface WorkerStateMessage {
  type: 'workerState';
  payload: {
    workerId: number;
    active?: boolean;
    taskId?: string;
    tokenUsage?: string;
    currentTool?: string;
    workerKind?: 'claude' | 'codex' | 'gemini';
  };
}

export interface FullStateMessage {
  type: 'fullState';
  payload: SchedulerFullState;
}

export interface HelloMessage {
  type: 'hello';
  serverTime: string;
  version: string;
}

export interface PongMessage {
  type: 'pong';
  ts: number;
}

export interface ErrorMessage {
  type: 'error';
  message: string;
}

export interface FileLoadedMessage {
  type: 'fileLoaded';
  payload: {
    filePath: string;
    projectRoot: string;
    tasks: Task[];
  };
}

export interface ExportLogsResponseMessage {
  type: 'exportLogsResponse';
  payload: {
    content: string;
  };
}

export interface IssueReportedMessage {
  type: 'issueReported';
  payload: {
    issue: Issue;
  };
}

export interface IssueUpdateMessage {
  type: 'issueUpdate';
  payload: {
    issueId: string;
    status: IssueStatus;
  };
}

export interface IssuesListMessage {
  type: 'issuesList';
  payload: {
    issues: Issue[];
  };
}

export type ServerMessage =
  | TaskUpdateMessage
  | WorkerLogMessage
  | ProgressMessage
  | SchedulerStateMessage
  | WorkerStateMessage
  | FullStateMessage
  | HelloMessage
  | PongMessage
  | ErrorMessage
  | FileLoadedMessage
  | ExportLogsResponseMessage
  | IssueReportedMessage
  | IssueUpdateMessage
  | IssuesListMessage;

// ============================================================
// Client → Server Messages
// ============================================================

export interface LoadFileMessage {
  type: 'loadFile';
  payload: {
    filePath: string;
  };
}

export interface StartMessage {
  type: 'start';
  payload: {
    maxParallel: number;
  };
}

export interface PauseMessage {
  type: 'pause';
}

export interface ResumeMessage {
  type: 'resume';
}

export interface StopMessage {
  type: 'stop';
}

export interface SendToWorkerMessage {
  type: 'sendToWorker';
  payload: {
    workerId: number;
    content: string;
  };
}

export interface KillWorkerMessage {
  type: 'killWorker';
  payload: {
    workerId: number;
  };
}

export interface ExportLogsMessage {
  type: 'exportLogs';
}

export interface PingMessage {
  type: 'ping';
  ts: number;
}

export type ClientMessage =
  | LoadFileMessage
  | StartMessage
  | PauseMessage
  | ResumeMessage
  | StopMessage
  | SendToWorkerMessage
  | KillWorkerMessage
  | ExportLogsMessage
  | PingMessage;

// ============================================================
// Utility Functions
// ============================================================

/**
 * Generates a unique run ID for scheduler sessions.
 * Uses crypto.randomUUID() when available, falls back to timestamp-based ID.
 */
export function generateRunId(): string {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) {
    return crypto.randomUUID();
  }
  // Fallback for environments without crypto.randomUUID
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 10);
  return `${timestamp}-${random}`;
}
